docker run -d \
-e "KONG_ROLE=data_plane" \
-e "KONG_DATABASE=off" \
-e "KONG_VITALS=off" \
-e "KONG_CLUSTER_MTLS=pki" \
-e "KONG_CLUSTER_CONTROL_PLANE=a0998d03be.eu.cp0.konghq.com:443" \
-e "KONG_CLUSTER_SERVER_NAME=a0998d03be.eu.cp0.konghq.com" \
-e "KONG_CLUSTER_TELEMETRY_ENDPOINT=a0998d03be.eu.tp0.konghq.com:443" \
-e "KONG_CLUSTER_TELEMETRY_SERVER_NAME=a0998d03be.eu.tp0.konghq.com" \
-e "KONG_CLUSTER_CERT=-----BEGIN CERTIFICATE-----
MIICBTCCAaygAwIBAgIBATAKBggqhkjOPQQDBDA0MTIwCQYDVQQGEwJFVTAlBgNV
BAMeHgBrAG8AbgBuAGUAYwB0AC0AZABlAG0AbwBfAGMAcDAeFw0yNTAyMjUxMDAx
MjhaFw0zNTAyMjUxMDAxMjhaMDQxMjAJBgNVBAYTAkVVMCUGA1UEAx4eAGsAbwBu
AG4AZQBjAHQALQBkAGUAbQBvAF8AYwBwMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcD
QgAEeoRCsKRuHEekReF9P/eDn9CofpwkxIpx5/ZQ7xA6bnrbH5UwxsTVIp5ZvUnL
m8ebkmVZtMNBhQED/R/KQTcpVaOBrjCBqzAMBgNVHRMBAf8EAjAAMAsGA1UdDwQE
AwIABjAdBgNVHSUEFjAUBggrBgEFBQcDAQYIKwYBBQUHAwIwFwYJKwYBBAGCNxQC
BAoMCGNlcnRUeXBlMCMGCSsGAQQBgjcVAgQWBBQBAQEBAQEBAQEBAQEBAQEBAQEB
ATAcBgkrBgEEAYI3FQcEDzANBgUpAQEBAQIBCgIBFDATBgkrBgEEAYI3FQEEBgIE
ABQACjAKBggqhkjOPQQDBANHADBEAiB4u0kzDW6dYXhV24yOc3yCyxArkLmJgX7L
oI6WAza/kQIgU/s/fX4ruOsFXT4lbJtRSqFs7p/gILoVCe8b3vHU3IY=
-----END CERTIFICATE-----" \
-e "KONG_CLUSTER_CERT_KEY=-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgRNNWpmmciVJB18Jo
8ehwXw0OkhtcJ/WGrHUkyhc6R0OgCgYIKoZIzj0DAQehRANCAAR6hEKwpG4cR6RF
4X0/94Of0Kh+nCTEinHn9lDvEDpuetsflTDGxNUinlm9Scubx5uSZVm0w0GFAQP9
H8pBNylV
-----END PRIVATE KEY-----" \
-e "KONG_LUA_SSL_TRUSTED_CERTIFICATE=system" \
-e "KONG_KONNECT_MODE=on" \
-e "KONG_CLUSTER_DP_LABELS=created-by:quickstart,type:docker-macOsArmOS" \
-e "KONG_ROUTER_FLAVOR=expressions" \
-p 8000:8000 \
-p 8443:8443 \
kong/kong-gateway:3.9