name: Publish API

on:
  workflow_dispatch:
    inputs:
      openapi_spec:
        description: "Path to the OpenAPI Specification file"
        required: true
        type: string
        default: "./oas.yaml"
      konnect_server_url:
        description: "Kong Konnect server url"
        type: string
        default: "https://eu.api.konghq.com"
      control_plane_name:
        description: "Kong Konnect control plane name"
        type: string
        required: true
        default: "demo_cp"
      api_name:
        description: 'API Name'
        type: string
        required: false
        default: 'petstore'
      organization:
        description: 'Organization'
        type: string
        required: false
        default: 'bankong'

env:
  DECK_API_NAME: transactions-api
  DECK_ORGANIZATION: ${{ inputs.organization }} # To be used as a tag
  DECK_CONFIG_OWNER: team1 # To be used as a tag

jobs:
  publish-api:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: kong/setup-inso@v1
        with:
          inso-version: 10.1.0

      # Install Docker Compose
      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.20.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version

      - name: Install extra rulesets for Spectral
        run: |
          npm install --save -D @stoplight/spectral-owasp-ruleset@^2.0

      - name: spin up demo server from docker compose kong.yaml
        run: |
          docker-compose up -d

      - name: Lint OpenAPI Specification
        run: |
          inso lint spec "Transactions API of BanKonG 1.1.0"

      - name: Run tests
        run: |
          inso run test "Demo test suite" --env local

      - name: Bring the mock server down
        run: |
          docker-compose down

      - name: DeckOps
        run: |

          # Convert OpenAPI Specification to Kong Gateway configuration
          cat ${{ inputs.openapi_spec }} | deck file openapi2kong > kong.yaml

          # Add plugins to the Kong Gateway configuration
          cat kong.yaml | deck file add-plugins \
            plugins/rate-limiting.yaml -o kong.yaml

          # Patch the Kong Gateway configuration
          cat kong.yaml | deck file patch patches/select_tags.yaml -o kong.yaml

          # Validate Generated Kong Gateway configuration
          deck file validate kong.yaml

          # Sync Kong Gateway configuration
          deck gateway sync kong.yaml  \
            --konnect-addr="${{ inputs.konnect_server_url }}" \
            --konnect-token="${{ secrets.KONNECT_PAT }}" \
            --konnect-control-plane-name="${{ inputs.control_plane_name }}"

